### ISSUE TITLE
cannot upload multiple files to Sakai 

### ISSUE THREAD

**Issue by cnorth21** [mikeizbicki/cmc-csci145-math166#38]
Hi Mike ! I am having trouble uploading multiple screenshots/files to the Sakai dropbox.  Should I put both screenshots into a PDF instead of uploading both of them? Thanks !

**Comment by mikeizbicki** [comment]
This should be fixed now.

**Comment by nsamko** [comment]
I faced the same issue and still cannot upload both screenshots, just one :(

**Comment by mikeizbicki** [comment]
Hmm... looks like my last fix didn't work, but I've just tried fixing it again.  Hopefully it worked this time.
